// This file was generated by silverstripe/tx-translator from client/lang/src/cs.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('cs', {
    "ElementAddElementPopover.SEARCH_BLOCKS": "Prohledat bloky",
    "ElementAddNewButton.ADD_BLOCK": "Přidat blok",
    "ElementArchiveAction.ARCHIVE": "Archiv",
    "ElementArchiveAction.CONFIRM_DELETE": "Jste si jistí, že chcete blok odeslat do archivu?",
    "ElementArchiveAction.CONFIRM_DELETE_AND_UNPUBLISH": "Varování: Tento blok bude před odesláním do archivu označen jako nezveřejněný. Opravdu chcete pokračovat?",
    "ElementEditForm.ERROR_NOTIFICATION": "Chyba při zobrazení formuláře úprav tohoto bloku",
    "ElementHeader.EXPAND": "Zobrazit editovatelná pole",
    "ElementHeader.NOTITLE": "Nepojmenovaný {type} blok",
    "ElementHeader.STATE_DRAFT": "Položka dosud nebyla zveřejněna",
    "ElementHeader.STATE_MODIFIED": "Položka obsahuje nezveřejněné úpravy",
    "ElementList.ADD_BLOCKS": "Přidat bloky a umístit obsah",
    "ElementPublishAction.ERROR_NOTIFICATION": "Chyba při zveřejnění '{title}'",
    "ElementPublishAction.PUBLISH": "Zveřejnit",
    "ElementPublishAction.SUCCESS_NOTIFICATION": "Úspěšně zveřejněno '{title}'",
    "ElementSaveAction.ERROR_NOTIFICATION": "Chyba při ukládání '{title}'",
    "ElementSaveAction.SAVE": "Uložit",
    "ElementSaveAction.SUCCESS_NOTIFICATION": "Úspěšně uloženo '{title}'",
    "ElementSummary.NO_PREVIEW": "Náhled není k dispozici",
    "ElementUnpublishAction.ERROR_NOTIFICATION": "Chyba při zrušení zveřejnění '{title}'",
    "ElementUnpublishAction.SUCCESS_NOTIFICATION": "'{title}' odstraněno ze zveřejněných stránek",
    "ElementUnpublishAction.UNPUBLISH": "Nezveřejnit",
    "ElementalElement.TITLE": "Upravit blok {type}",
    "HistoricElementView.BLOCK_HISTORY": "Zobrazit blok"
});
}