// This file was generated by silverstripe/cow from client/lang/src/en.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "ElementArchiveAction.CONFIRM_DELETE": "Are you sure you want to send this block to the archive?",
    "ElementArchiveAction.CONFIRM_DELETE_AND_UNPUBLISH": "Warning: This block will be unpublished before being sent to the archive. Are you sure you want to proceed?",
    "ElementArchiveAction.ARCHIVE": "Archive",
    "ElementArchiveAction.ARCHIVE_PERMISSION_DENY": "Archive, insufficient permissions",
    "ElementArchiveAction.DUPLICATE": "Duplicate",
    "ElementArchiveAction.DUPLICATE_PERMISSION_DENY": "Duplicate, insufficient permissions",
    "ElementHeader.BROKEN": "This element is of obsolete type {type}.",
    "ElementHeader.NOTITLE": "Untitled {type} block",
    "ElementPublishAction.SUCCESS_NOTIFICATION": "Published '{title}' successfully",
    "ElementPublishAction.ERROR_NOTIFICATION": "Error publishing '{title}'",
    "ElementPublishAction.PUBLISH": "Publish",
    "ElementPublishAction.PUBLISH_PERMISSION_DENY": "Publish, insufficient permissions",
    "ElementSaveAction.SUCCESS_NOTIFICATION": "Saved '{title}' successfully",
    "ElementSaveAction.ERROR_NOTIFICATION": "Error saving '{title}'",
    "ElementSaveAction.SAVE": "Save",
    "ElementUnpublishAction.SUCCESS_NOTIFICATION": "Removed '{title}' from the published page",
    "ElementUnpublishAction.ERROR_NOTIFICATION": "Error unpublishing '{title}'",
    "ElementUnpublishAction.UNPUBLISH": "Unpublish",
    "ElementUnpublishAction.UNPUBLISH_PERMISSION_DENY": "Unpublish, insufficient permissions",
    "ElementAddElementPopover.SEARCH_BLOCKS": "Search blocks",
    "ElementAddNewButton.ADD_BLOCK": "Add block",
    "ElementalElement.ARCHIVE_BROKEN": "Archive this block",
    "ElementalElement.BROKEN_DESCRIPTION": "This block is broken and will not display on the front-end. You can archive it to remove it from this elemental area.",
    "ElementalElement.BROKEN_DESCRIPTION_TITLE": "This block had the title \"{title}\". It is broken and will not display on the front-end. You can archive it to remove it from this elemental area.",
    "ElementalElement.TITLE": "Edit this {type} block",
    "ElementalElement.CHILD_RENDERING_ERROR": "Something went wrong with this block. Please try saving and refreshing the CMS.",
    "ElementList.ADD_BLOCKS": "Add blocks to place your content",
    "ElementHeader.STATE_DRAFT": "Item has not been published yet",
    "ElementHeader.STATE_MODIFIED": "Item has unpublished changes",
    "ElementHeader.EXPAND": "Show editable fields",
    "ElementEditForm.ERROR_NOTIFICATION": "Error displaying the edit form for this block",
    "ElementSummary.NO_PREVIEW": "No preview available",
    "HistoricElementView.VIEW_BLOCK_HISTORY": "Block history",
    "HistoricElementView.BLOCK_HISTORY": "View block"
});
}