// This file was generated by silverstripe/cow from client/lang/src/fi.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fi', {
    "ElementArchiveAction.CONFIRM_DELETE": "Haluatko varmasti siirtää tämän palikan arkistoon?",
    "ElementArchiveAction.CONFIRM_DELETE_AND_UNPUBLISH": "Varoitus: tämä palikka poistetaan julkaisusta ennen kuin se siirretään arkistoon. Haluatko varmasti jatkaa?",
    "ElementArchiveAction.ARCHIVE": "Arkistoi",
    "ElementHeader.NOTITLE": "Nimetön {type} palikka",
    "ElementPublishAction.SUCCESS_NOTIFICATION": "Julkaistiin '{title}' onnistuneesti",
    "ElementPublishAction.ERROR_NOTIFICATION": "Virhe julkaistaessa '{title}'",
    "ElementPublishAction.PUBLISH": "Julkaise",
    "ElementSaveAction.SUCCESS_NOTIFICATION": "Tallennettiin '{title}' onnistuneesti",
    "ElementSaveAction.ERROR_NOTIFICATION": "Virhe tallennettaessa '{title}'",
    "ElementSaveAction.SAVE": "Tallenna",
    "ElementUnpublishAction.SUCCESS_NOTIFICATION": "Poistettiin '{title}' julkaistulta sivulta",
    "ElementUnpublishAction.ERROR_NOTIFICATION": "Virhe poistettaessa julkaisua » '{title}'",
    "ElementUnpublishAction.UNPUBLISH": "Poista julkaisusta",
    "ElementAddElementPopover.SEARCH_BLOCKS": "Etsi palikoita",
    "ElementAddNewButton.ADD_BLOCK": "Lisää palikka",
    "ElementalElement.TITLE": "Muokkaa {type} palikkaa",
    "ElementList.ADD_BLOCKS": "Lisää palikoita julkaistaksesi sisältöä",
    "ElementHeader.STATE_DRAFT": "Kohdetta ei ole vielä julkaistu",
    "ElementHeader.STATE_MODIFIED": "Kohteella on tallentamattomia muutoksia",
    "ElementHeader.EXPAND": "Näytä muokattavat kentät",
    "ElementEditForm.ERROR_NOTIFICATION": "Virhe näytettäessä muokkauskenttää tälle palikalle",
    "ElementSummary.NO_PREVIEW": "Ei esikatselua",
    "HistoricElementView.BLOCK_HISTORY": "Näytä palikka",
    "ElementArchiveAction.ARCHIVE_PERMISSION_DENY": "Archive, insufficient permissions",
    "ElementArchiveAction.DUPLICATE": "Duplicate",
    "ElementArchiveAction.DUPLICATE_PERMISSION_DENY": "Duplicate, insufficient permissions",
    "ElementPublishAction.PUBLISH_PERMISSION_DENY": "Publish, insufficient permissions",
    "ElementUnpublishAction.UNPUBLISH_PERMISSION_DENY": "Unpublish, insufficient permissions",
    "ElementalElement.CHILD_RENDERING_ERROR": "Something went wrong with this block. Please try saving and refreshing the CMS.",
    "HistoricElementView.VIEW_BLOCK_HISTORY": "Block history"
});
}