// This file was generated by silverstripe/tx-translator from client/lang/src/fi.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fi', {
    "ElementAddElementPopover.SEARCH_BLOCKS": "Etsi palikoita",
    "ElementAddNewButton.ADD_BLOCK": "Lisää palikka",
    "ElementArchiveAction.ARCHIVE": "Arkistoi",
    "ElementArchiveAction.CONFIRM_DELETE": "Haluatko varmasti siirtää tämän palikan arkistoon?",
    "ElementArchiveAction.CONFIRM_DELETE_AND_UNPUBLISH": "Varoitus: tämä palikka poistetaan julkaisusta ennen kuin se siirretään arkistoon. Haluatko varmasti jatkaa?",
    "ElementEditForm.ERROR_NOTIFICATION": "Virhe näytettäessä muokkauskenttää tälle palikalle",
    "ElementHeader.EXPAND": "Näytä muokattavat kentät",
    "ElementHeader.NOTITLE": "Nimetön {type} palikka",
    "ElementHeader.STATE_DRAFT": "Kohdetta ei ole vielä julkaistu",
    "ElementHeader.STATE_MODIFIED": "Kohteella on tallentamattomia muutoksia",
    "ElementList.ADD_BLOCKS": "Lisää palikoita julkaistaksesi sisältöä",
    "ElementPublishAction.ERROR_NOTIFICATION": "Virhe julkaistaessa '{title}'",
    "ElementPublishAction.PUBLISH": "Julkaise",
    "ElementPublishAction.SUCCESS_NOTIFICATION": "Julkaistiin '{title}' onnistuneesti",
    "ElementSaveAction.ERROR_NOTIFICATION": "Virhe tallennettaessa '{title}'",
    "ElementSaveAction.SAVE": "Tallenna",
    "ElementSaveAction.SUCCESS_NOTIFICATION": "Tallennettiin '{title}' onnistuneesti",
    "ElementSummary.NO_PREVIEW": "Ei esikatselua",
    "ElementUnpublishAction.ERROR_NOTIFICATION": "Virhe poistettaessa julkaisua » '{title}'",
    "ElementUnpublishAction.SUCCESS_NOTIFICATION": "Poistettiin '{title}' julkaistulta sivulta",
    "ElementUnpublishAction.UNPUBLISH": "Poista julkaisusta",
    "ElementalElement.TITLE": "Muokkaa {type} palikkaa",
    "HistoricElementView.BLOCK_HISTORY": "Näytä palikka"
});
}