// This file was generated by silverstripe/cow from client/lang/src/fr.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fr', {
    "ElementArchiveAction.CONFIRM_DELETE": "Êtes-vous sûr de vouloir envoyer ce bloc aux archives ?",
    "ElementArchiveAction.CONFIRM_DELETE_AND_UNPUBLISH": "Attention: Ce bloc sera dépublié avant d'être envoyé aux archives. Êtes-vous sûr de vouloir continuer ?",
    "ElementArchiveAction.ARCHIVE": "Archiver",
    "ElementArchiveAction.DUPLICATE": "Dupliquer",
    "ElementHeader.NOTITLE": "Bloc {type} sans titre",
    "ElementPublishAction.SUCCESS_NOTIFICATION": "'{title}' publié avec succès",
    "ElementPublishAction.ERROR_NOTIFICATION": "Erreur à la publication de '{title}'",
    "ElementPublishAction.PUBLISH": "Publier",
    "ElementSaveAction.SUCCESS_NOTIFICATION": "'{title}' sauvegardé avec succès",
    "ElementSaveAction.ERROR_NOTIFICATION": "Erreur à la sauvegarde de '{title}'",
    "ElementSaveAction.SAVE": "Sauvegarder",
    "ElementUnpublishAction.SUCCESS_NOTIFICATION": "'{title}' retiré de la page publiée",
    "ElementUnpublishAction.ERROR_NOTIFICATION": "Erreur à la dépublication de '{title}'",
    "ElementUnpublishAction.UNPUBLISH": "Dépublier",
    "ElementAddElementPopover.SEARCH_BLOCKS": "Chercher blocs",
    "ElementAddNewButton.ADD_BLOCK": "Ajouter bloc",
    "ElementalElement.TITLE": "Éditer ce bloc {type}",
    "ElementList.ADD_BLOCKS": "Ajouter des blocs pour placer votre contenu",
    "ElementHeader.STATE_DRAFT": "L'élément n'a pas encore été publié",
    "ElementHeader.STATE_MODIFIED": "L'élément a des changements non publiés",
    "ElementHeader.EXPAND": "Montrer les champs éditables",
    "ElementEditForm.ERROR_NOTIFICATION": "Erreur à l'affichage du formulaire d'édition pour ce bloc",
    "ElementSummary.NO_PREVIEW": "Aucune prévisualisation disponible",
    "HistoricElementView.BLOCK_HISTORY": "Voir bloc"
});
}