// This file was generated by silverstripe/tx-translator from client/lang/src/it.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('it', {
    "ElementAddElementPopover.SEARCH_BLOCKS": "Cerca blocchi",
    "ElementAddNewButton.ADD_BLOCK": "Aggiungi blocco",
    "ElementArchiveAction.ARCHIVE": "Archivio",
    "ElementArchiveAction.CONFIRM_DELETE": "Sei sicuro di voler inviare questo blocco all'archivio?",
    "ElementArchiveAction.CONFIRM_DELETE_AND_UNPUBLISH": "Attenzione: questo blocco non sarà pubblicato prima di essere inviato all'archivio. Sei sicuro di voler procedere?",
    "ElementEditForm.ERROR_NOTIFICATION": "Errore durante la visualizzazione del modulo di modifica per questo blocco",
    "ElementHeader.EXPAND": "Mostra campi modificabili",
    "ElementHeader.NOTITLE": "Blocco {type} senza titolo",
    "ElementHeader.STATE_DRAFT": "L'articolo non è stato ancora pubblicato",
    "ElementHeader.STATE_MODIFIED": "L'articolo ha modifiche non pubblicate",
    "ElementList.ADD_BLOCKS": "Aggiungi blocchi per posizionare il tuo contenuto",
    "ElementPublishAction.ERROR_NOTIFICATION": "Errore di pubblicazione '{title}'",
    "ElementPublishAction.PUBLISH": "Pubblica",
    "ElementPublishAction.SUCCESS_NOTIFICATION": "Pubblicato '{title}' con successo",
    "ElementSaveAction.ERROR_NOTIFICATION": "Errore durante il salvataggio '{title}'",
    "ElementSaveAction.SAVE": "Salva",
    "ElementSaveAction.SUCCESS_NOTIFICATION": "Salvato '{title}' con successo",
    "ElementSummary.NO_PREVIEW": "Nessuna anteprima disponibile",
    "ElementUnpublishAction.ERROR_NOTIFICATION": "Errore di annullamento della pubblicazione '{title}'",
    "ElementUnpublishAction.SUCCESS_NOTIFICATION": "Rimosso '{title}' dalla pagina pubblicata",
    "ElementUnpublishAction.UNPUBLISH": "Non pubblicato",
    "ElementalElement.TITLE": "Modifica questo blocco {type} ",
    "HistoricElementView.BLOCK_HISTORY": "Visualizza il blocco"
});
}