// This file was generated by silverstripe/cow from client/lang/src/pl.json.
// See https://github.com/silverstripe/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "ElementArchiveAction.CONFIRM_DELETE": "Czy na pewno chcesz wysłać ten blok do archiwum?",
    "ElementArchiveAction.CONFIRM_DELETE_AND_UNPUBLISH": "Ostrzeżenie: ten blok będzie szkicem przed wysłaniem do archiwum. Na pewno chcesz kontynuować?",
    "ElementArchiveAction.ARCHIVE": "Archiwum",
    "ElementArchiveAction.ARCHIVE_PERMISSION_DENY": "Archiwum, niewystarczające uprawnienia",
    "ElementArchiveAction.DUPLICATE": "Duplikat",
    "ElementArchiveAction.DUPLICATE_PERMISSION_DENY": "Duplikat, niewystarczające uprawnienia",
    "ElementHeader.NOTITLE": "Nienazwany {type} blok",
    "ElementPublishAction.SUCCESS_NOTIFICATION": "Opublikowano „{title}” pomyślnie",
    "ElementPublishAction.ERROR_NOTIFICATION": "Błąd podczas publikowania „{title}”",
    "ElementPublishAction.PUBLISH": "Publikuj",
    "ElementPublishAction.PUBLISH_PERMISSION_DENY": "Publikuj, niewystarczające uprawnienia",
    "ElementSaveAction.SUCCESS_NOTIFICATION": "Opublikowano „{title}” pomyślnie",
    "ElementSaveAction.ERROR_NOTIFICATION": "Błąd podczas zapisywania „{title}”",
    "ElementSaveAction.SAVE": "Zapisz",
    "ElementUnpublishAction.SUCCESS_NOTIFICATION": "Usunięto „{title}” z opublikowanej strony",
    "ElementUnpublishAction.ERROR_NOTIFICATION": "Błąd podczas cofania publikacji „{title}”",
    "ElementUnpublishAction.UNPUBLISH": "Cofnij publikację",
    "ElementUnpublishAction.UNPUBLISH_PERMISSION_DENY": "Cofnij publikację, niewystarczające uprawnienia",
    "ElementAddElementPopover.SEARCH_BLOCKS": "Wyszukaj",
    "ElementAddNewButton.ADD_BLOCK": "Dodaj blok",
    "ElementalElement.TITLE": "Edytuj {type} blok",
    "ElementalElement.CHILD_RENDERING_ERROR": "Coś poszło nie tak z tym blokiem. Prosimy raz jeszcze zapisz, potem odświeżmy przeglądarkę – zakładkę z CMSem.",
    "ElementList.ADD_BLOCKS": "Dodaj bloki, aby umieścić swoją treść",
    "ElementHeader.STATE_DRAFT": "Przedmiot nie został jeszcze opublikowany",
    "ElementHeader.STATE_MODIFIED": "Element ma nieopublikowane zmiany",
    "ElementHeader.EXPAND": "Pokaż pola możliwe do edycji",
    "ElementEditForm.ERROR_NOTIFICATION": "Błąd podczas wyświetlania formularza edycji dla tego bloku",
    "ElementSummary.NO_PREVIEW": "Brak możliwego podglądu",
    "HistoricElementView.VIEW_BLOCK_HISTORY": "Historia",
    "HistoricElementView.BLOCK_HISTORY": "Widok bloku"
});
}