// This file was generated by silverstripe/tx-translator from client/lang/src/sl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "ElementAddElementPopover.SEARCH_BLOCKS": "Najdi gradnik",
    "ElementAddNewButton.ADD_BLOCK": "Dodaj gradnik",
    "ElementArchiveAction.ARCHIVE": "Arhiv",
    "ElementArchiveAction.CONFIRM_DELETE": "Želite arhivirati izbrani gradnik?",
    "ElementArchiveAction.CONFIRM_DELETE_AND_UNPUBLISH": "Opozorilo: Gradnik bo umaknjen iz objave preden ga bomo arhivirali. Želite nadaljevati?",
    "ElementEditForm.ERROR_NOTIFICATION": "Napaka pri prikazu obrazca za urejanje tega gradnika",
    "ElementHeader.EXPAND": "Prikaži polja, ki jih je mogoče urejati",
    "ElementHeader.NOTITLE": "{type} gradnik brez naslova",
    "ElementHeader.STATE_DRAFT": "Ta gradnik še ni objavljen",
    "ElementHeader.STATE_MODIFIED": "Spremembe za ta gradnik še niso shranjene ",
    "ElementList.ADD_BLOCKS": "Dodajte gradnik z vsebino",
    "ElementPublishAction.ERROR_NOTIFICATION": "Napaka pri objavi '{title}'",
    "ElementPublishAction.PUBLISH": "Objavi",
    "ElementPublishAction.SUCCESS_NOTIFICATION": "Objavili smo '{title}'",
    "ElementSaveAction.ERROR_NOTIFICATION": "Napaka pri shranjevanju '{title}'",
    "ElementSaveAction.SAVE": "Shrani",
    "ElementSaveAction.SUCCESS_NOTIFICATION": "Shranili smo '{title}'",
    "ElementSummary.NO_PREVIEW": "Predogled ni na voljo",
    "ElementUnpublishAction.ERROR_NOTIFICATION": "Napaka pri umiku '{title}' iz objave",
    "ElementUnpublishAction.SUCCESS_NOTIFICATION": "Z objavljene strani smo odstranili '{title}'",
    "ElementUnpublishAction.UNPUBLISH": "Umakni iz objave",
    "ElementalElement.TITLE": "Urejanje gradnika {type}",
    "HistoricElementView.BLOCK_HISTORY": "Prikaži gradnik"
});
}