// This file was generated by silverstripe/tx-translator from client/lang/src/sv.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "ElementAddElementPopover.SEARCH_BLOCKS": "Sök block",
    "ElementAddNewButton.ADD_BLOCK": "Lägg till block",
    "ElementArchiveAction.ARCHIVE": "Arkiv",
    "ElementArchiveAction.ARCHIVE_PERMISSION_DENY": "Arkiv, otillräckliga behörigheter",
    "ElementArchiveAction.CONFIRM_DELETE": "Är du säker på att du vill arkivera detta block?",
    "ElementArchiveAction.CONFIRM_DELETE_AND_UNPUBLISH": "Varning: Detta block kommer bli avpublicerat före det skickas till arkivet. Är du säker på att du vill fortsätta?",
    "ElementArchiveAction.DUPLICATE": "Duplicera",
    "ElementArchiveAction.DUPLICATE_PERMISSION_DENY": "Duplicera, otillräckliga behörigheter",
    "ElementEditForm.ERROR_NOTIFICATION": "Det gick inte att visa redigeringsformuläret för detta block",
    "ElementHeader.BROKEN": "Detta element är av föråldrad typ {type}.",
    "ElementHeader.EXPAND": "Visa redigerbara fält",
    "ElementHeader.NOTITLE": "Namnlöst {type} block",
    "ElementHeader.STATE_DRAFT": "Detta är inte publicerat ännu",
    "ElementHeader.STATE_MODIFIED": "Detta har opublicerade ändringar",
    "ElementList.ADD_BLOCKS": "Lägg till block för att lägga till ditt innehåll ",
    "ElementPublishAction.ERROR_NOTIFICATION": "Misslyckades vid publicering av '{title}'",
    "ElementPublishAction.PUBLISH": "Publicera",
    "ElementPublishAction.PUBLISH_PERMISSION_DENY": "Publicera, otillräckliga behörigheter",
    "ElementPublishAction.SUCCESS_NOTIFICATION": "Publicerade '{title}'",
    "ElementSaveAction.ERROR_NOTIFICATION": "Misslyckades att spara '{title}'",
    "ElementSaveAction.SAVE": "Spara",
    "ElementSaveAction.SUCCESS_NOTIFICATION": "Sparade '{title}'",
    "ElementSummary.NO_PREVIEW": "Ingen förhandsgranskning tillgänglig",
    "ElementUnpublishAction.ERROR_NOTIFICATION": "Misslyckades att avpublicera '{title}'",
    "ElementUnpublishAction.SUCCESS_NOTIFICATION": "Raderade '{title}' från publicerade sidan",
    "ElementUnpublishAction.UNPUBLISH": "Avpublicera",
    "ElementUnpublishAction.UNPUBLISH_PERMISSION_DENY": "Avpublicera, otillräckliga behörigheter",
    "ElementalElement.ARCHIVE_BROKEN": "Arkivera detta block",
    "ElementalElement.BROKEN_DESCRIPTION": "Detta block är trasigt och kommer inte att visas på webbsidan. Du kan arkivera det för att ta bort det från detta blockområde.",
    "ElementalElement.BROKEN_DESCRIPTION_TITLE": "Detta block hade titeln \"{title}\". Den är trasig och kommer inte att visas på webbsidan. Du kan arkivera det för att ta bort det från detta blockområde. ",
    "ElementalElement.CHILD_RENDERING_ERROR": "Något gick fel med det här blocket. Försök att spara och uppdatera CMS.",
    "ElementalElement.TITLE": "Redigera detta {type}-block",
    "HistoricElementView.BLOCK_HISTORY": "Visa block",
    "HistoricElementView.VIEW_BLOCK_HISTORY": "Blockhistorik"
});
}